contact_links:
  - name: Submit an RFC (Request for change) to TinaCMS Maintainers
    url: https://github.com/tinacms/rfcs
    about: If you'd like to submit an RFC for an official Tina package found at https://github.com/tinacms please submit a package to the official RFC repo linked here.
  - name: Submit an RFC (Request for change)
    url: https://github.com/tinalabs/rfcs/blob/main/_example.md
    about: If you'd like to submit an RFC for a change to an existing package, or to suggest a new feature, package, or experiment, please submit a pull request using the template linked to here.
